### ISSUE TITLE
Interest in Bright Peeps

### ISSUE THREAD

**Issue by BradyJ9** [BYUCS452F2021/bright-peeps#1]
I have interest in the Bright Peeps project and connect and identify with its goals and purpose.  With social platforms seemingly becoming a more divisive, controversial space,  I love the idea of bringing brightness to the internet.  Through our team I hope we are able to create a marketable, easy-to-use product that is effective in bringing about wholesomeness into the daily tech routine of its users.  

I am able to offer programming experience in ASP.NET Core's C# Web API framework.  I have familiarity in React and in SQL and NoSQL databases as well.  I am open to learning, being flexible, and helping where needed.

**Comment by rogvc** [comment]
You're in!
