### ISSUE TITLE
Hi I'm Interested!

### ISSUE THREAD

**Issue by johnny123214133** [BYUCS452F2021/bright-peeps#2]
Hi, I’m Zach.  It’s a goal of mine to be the good I want to see in the world, and to that end I see how Bright Peeps can be a part of that good.  I am currently taking CS 260 but have had previous experience with basic web development languages.  I’ve also taken CS 340 where I built a simple social media platform, so there’s a lot overlap there, at least in project design.  I’ve used MySQL for work, SQLite and DynamoDB in the CS program, but I’m open to learning whatever is needed.

**Comment by rogvc** [comment]
Sweet! Welcome to the team! :)
